### ISSUE TITLE
Set up my own server

### ISSUE THREAD

**Issue by Fishermanykx** [Shadudev/HollowKnight.MultiWorld#35]
Hello! I have a problem while reading [Setting up a server](https://github.com/Shadudev/HollowKnight.MultiWorld/blob/master/ItemSyncMod/README.md#setting-up-a-server) Do I need to own a server with public IP address to set up the server? Can I just set up the server on my personal computer which connects to a family WiFi? Thanks for your reply.

**Comment by Shadudev** [comment]
I will prefice by saying that there is a public server available to all to play on, so you and your friends can easily use it!
The IP should be set in the mod when installing for the first time, but just in case it isn't: `18.189.16.129` .

As for your question; when you run a server on your personal computer, people who are also connected to your family WiFi should be able to connect by writing your local IP (looks like 10.x.x.x / 172.x.x.x / 192.168.x.x). 

If you want other people to connect to it, you will need to configure in your router settings to `port forward` the port 38281 (unless configured otherwise in `config.json`) for TCP communications to the computer that is running the server.
Once this is done, others should be able to connect to it by writing your public IP (head to sites like whatsmyip.com to see it).

There is no need to own anything in particular other than a personal machine for a minimal setup. The public server is running on an AWS instance I own that's active 24/7, keeping my PC and public IP completely out of the equation 🙃

**Comment by Shadudev** [comment]
If you have any further questions, feel free to reopen this issue or message me on Discord @ `Shadu#4196`
